const audioFiles = [
  ["Alis", "Drž hubu!", "files/alis_drz_hubu.mp3", 1],
  ["Alis", "Není problém!", "files/alis_neni_problem.mp3", 1],
  ["Alis", "Mi upadne čůrák!", "files/alis_upadne_curak.mp3", 1],
  ["BZX", "AAAAAAAA!", "files/bzx_aaaaaaa.mp3", 0.3],
  ["BZX", "Kreténskej idiot!", "files/bzx_kretenskej_idiot.mp3", 0.3],
  ["BZX", "Krypleee!", "files/bzx_krypleee.mp3", 1],
  ["BZX", "To je debil!", "files/bzx_to_je_debil.mp3", 0.3],
  ["Doktorilla", "Drž hubu!", "files/doktorilla_drz_hubu.mp3", 0.5],
  ["Medic", "Kulturní šok!", "files/medic_kulturni_sok.mp3", 0.7],
  ["Monstrum", "Mi nestojí!", "files/monstrum_nestoji.mp3", 1 ],
  ["Mysterion", "Běžím, vytahuju!", "files/mysterion_bezim_vytahuju.mp3", 0.8],
  ["Mysterion", "Já ho minul!", "files/mysterion_ja_ho_minul.mp3", 0.8],
  ["Mysterion", "Minul!", "files/mysterion_minul.mp3", 0.8],
  ["Palko", "Patro do patra!", "files/palko_patro_do_patra.mp3", 0.7],
  ["Palko", "Skrz kámen!", "files/palko_skrz_kamen.mp3", 0.7],
];
